title: "Atharva Kalange - Portfolio"
email: "your-email@example.com"
description: "My personal portfolio showcasing my projects and experience."
baseurl: ""  
url: "https://atharva9890.github.io"
theme: minima  
