title: "Atharva Kalange - Portfolio"
email: "your-email@example.com"
description: "My personal portfolio showcasing my projects and experience."
baseurl: ""  # Leave blank for GitHub Pages user site
url: "https://atharva9890.github.io"
theme: minima  # You can change this to another Jekyll theme
